# Generated by Django 3.0.8 on 2020-07-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('contactno', models.IntegerField(unique=True)),
                ('mailid', models.EmailField(max_length=254, unique=True)),
                ('courses', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
